{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-clinify
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/clinify_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/clinify/clinify_{{ version }}.tar.gz
  sha256: 9e5163dedd59bbe2e79c4b9d4f5683e314cc5b73315809d7dc9280ab567576bb

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    # The libstdc++.dll provided in libstdcxx v15.1.0 build h904f734_2
    # is missing `_ZSt21ios_base_library_initv`.
    # see: conda-forge/ctng-compilers-feedstock#174
    - libstdcxx !=14.3.0,!=15.1.0  # [win]
  host:
    - r-base
    - r-dplyr
    - r-flextable
    - r-htmltools
    - r-knitr
    - r-magrittr
    - r-officer
    - r-tidyselect
    - r-zoo
  run:
    - r-base
    - r-dplyr
    - r-flextable
    - r-htmltools
    - r-knitr
    - r-magrittr
    - r-officer
    - r-tidyselect
    - r-zoo
  run_constrained:
    - libstdcxx !=14.3.0,!=15.1.0           # [win]

test:
  commands:
    - $R -e "library('clinify')"           # [not win]
    - "\"%R%\" -e \"library('clinify')\""  # [win]

about:
  home: https://atorus-research.github.io/clinify/
  license: Apache-2.0
  summary: The primary motivation of this package is to take the things that are great about the R packages 'flextable' <https://davidgohel.github.io/flextable/> and 'officer' <https://davidgohel.github.io/officer/>, take the standard and complex pieces of formatting clinical tables for regulatory use, and simplify the tedious
    pieces.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
